"""Shared cancel-marker write path used by both the CLI and the dashboard API."""
import json
import re
import tempfile
from datetime import datetime, timezone
from pathlib import Path

# Matches the validation used for workflow_name in queries.py:45 and aligns
# with the UUID/slug shape of run_ids generated by the trigger and CLI.
RUN_ID_PATTERN = re.compile(r"^[a-zA-Z0-9-]+$")


class InvalidRunIdError(ValueError):
    """Raised when a run_id contains characters outside [A-Za-z0-9-]."""


def validate_run_id(run_id: str) -> None:
    """Reject run_ids that could escape events_dir via path traversal.

    Raises InvalidRunIdError when run_id does not match ^[a-zA-Z0-9-]+$.
    """
    if not run_id or not RUN_ID_PATTERN.match(run_id):
        raise InvalidRunIdError(
            f"Invalid run_id: must match {RUN_ID_PATTERN.pattern}"
        )


def write_cancel_marker(
    events_dir: Path,
    run_id: str,
    cancelled_by: str,
) -> Path:
    """Atomically write {events_dir}/{run_id}.cancel.

    The marker is created as a NamedTemporaryFile in events_dir (same
    filesystem, so rename is POSIX-atomic) and then renamed to the final
    path. Callers MUST catch InvalidRunIdError and translate it to their
    own error surface (HTTP 400, CLI exit, etc).

    Args:
        events_dir: Directory where the marker will be written. Created if missing.
        run_id: Run identifier. Must match ^[a-zA-Z0-9-]+$.
        cancelled_by: Identity recorded in the marker payload.

    Returns:
        Path to the final .cancel marker file.
    """
    validate_run_id(run_id)
    events_dir.mkdir(parents=True, exist_ok=True)

    payload = {
        "cancelled_by": cancelled_by,
        "cancelled_at": datetime.now(timezone.utc).isoformat(),
    }

    marker_path = events_dir / f"{run_id}.cancel"
    with tempfile.NamedTemporaryFile(
        mode="w",
        dir=events_dir,
        delete=False,
        suffix=".tmp",
    ) as tmp_file:
        json.dump(payload, tmp_file)
        tmp_path = Path(tmp_file.name)

    # POSIX-atomic rename (same filesystem guaranteed since tmp was in events_dir)
    tmp_path.rename(marker_path)
    return marker_path
