#!/usr/bin/env npx ts-node

/**
 * Write Implementation Skill
 * Captures planning outputs and writes implementation documents to project-docs
 *
 * Usage:
 *   npx tsx .claude/skills/project-docs/write-implementation.ts '{
 *     "topic": "Session Token Lifecycle Implementation",
 *     "content": "## Architecture\n\n- Token generation...",
 *     "sections": ["Token Generation", "Validation", "Expiration"],
 *     "relatedIssues": ["PROJ-345", "PROJ-346"],
 *     "tags": ["sessions", "tokens", "backend"],
 *     "reviewers": ["alice@platform.example.com"]
 *   }'
 */

import * as fs from 'fs';
import * as path from 'path';
import { exec } from 'child_process';
import { promisify } from 'util';

const execAsync = promisify(exec);

interface WriteImplementationParams {
  topic: string;
  content: string;
  sections?: string[];
  relatedIssues?: string[];
  tags?: string[];
  reviewers?: string[];
}

interface WriteImplementationResult {
  filePath: string;
  fileName: string;
  gitHash?: string;
  dualReviewTriggered: boolean;
  linkedIssues: string[];
  message: string;
  timestamp: string;
}

async function validateEnvironment(): Promise<{
  docsPath: string;
  projectRoot: string;
}> {
  const docsPath = process.env.TENANT_DOCS_PATH;
  const projectRoot = process.env.PROJECT_ROOT;

  if (!docsPath) {
    throw new Error('TENANT_DOCS_PATH environment variable not set');
  }

  if (!projectRoot) {
    throw new Error('PROJECT_ROOT environment variable not set');
  }

  if (!fs.existsSync(docsPath)) {
    throw new Error(`TENANT_DOCS_PATH does not exist: ${docsPath}`);
  }

  if (!fs.existsSync(projectRoot)) {
    throw new Error(`PROJECT_ROOT does not exist: ${projectRoot}`);
  }

  return { docsPath, projectRoot };
}

function generateFileName(topic: string): string {
  const date = new Date().toISOString().split('T')[0]; // YYYY-MM-DD
  const slug = topic
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-');

  return `${date}-${slug}.md`;
}

function formatImplementationDocument(
  params: WriteImplementationParams,
  fileName: string
): string {
  const timestamp = new Date().toISOString();
  const sections = params.sections || [];
  const tags = params.tags || [];
  const issues = params.relatedIssues || [];

  let frontmatter = `---
title: "${params.topic}"
date: ${timestamp}
type: implementation
status: draft
tags: [${tags.map((t) => `"${t}"`).join(', ')}]
linked_issues: [${issues.map((i) => `"${i}"`).join(', ')}]
---

`;

  let body = `# ${params.topic}\n\n`;
  body += `**Date**: ${timestamp.split('T')[0]}\n`;
  body += `**Status**: Draft (awaiting dual-agent review)\n`;
  body += `**File**: \`implementations/${fileName}\`\n\n`;

  if (issues.length > 0) {
    const jiraBaseUrl = process.env.JIRA_BASE_URL || 'https://your-org.atlassian.net';
    body += `## Related Jira Issues\n\n`;
    body += issues
      .map(
        (issue) =>
          `- [${issue}](${jiraBaseUrl}/browse/${issue})`
      )
      .join('\n');
    body += '\n\n';
  }

  if (params.reviewers && params.reviewers.length > 0) {
    body += `**Assigned Reviewers**: ${params.reviewers.join(', ')}\n\n`;
  }

  if (sections.length > 0) {
    body += `## Key Sections\n\n`;
    body += sections.map((s) => `- ${s}`).join('\n');
    body += '\n\n';
  }

  body += `## Implementation Plan\n\n${params.content}\n\n`;
  body += `---\n\n`;
  body += `**Document generated by write-implementation.ts skill**\n`;

  return frontmatter + body;
}

async function stageGitChanges(
  docsPath: string,
  fileName: string
): Promise<string> {
  try {
    const implPath = path.join(docsPath, 'implementations', fileName);

    await execAsync(`git add "${implPath}"`, { cwd: docsPath });

    const { stdout } = await execAsync(`git ls-files -s "${implPath}"`, {
      cwd: docsPath,
    });

    const hash = stdout.split(/\s+/)[1];
    return hash || 'staged';
  } catch (error) {
    console.warn('Could not retrieve git hash:', error);
    return 'staged';
  }
}

async function linkJiraIssues(
  issues: string[],
  fileName: string
): Promise<string[]> {
  const linkedIssues: string[] = [];

  for (const issue of issues) {
    try {
      // In production, this would call jira skills to add a link
      console.log(`[INFO] Would link ${issue} to ${fileName}`);
      linkedIssues.push(issue);
    } catch (error) {
      console.warn(`Failed to link issue ${issue}:`, error);
    }
  }

  return linkedIssues;
}

async function triggerDualAgentReview(
  params: WriteImplementationParams,
  fileName: string
): Promise<boolean> {
  try {
    const reviewTask = {
      type: 'implementation_review',
      file: fileName,
      topic: params.topic,
      relatedIssues: params.relatedIssues || [],
      reviewers: params.reviewers || ['agent:coder', 'agent:reviewer'],
      timestamp: new Date().toISOString(),
      status: 'pending',
    };

    console.log(
      `[INFO] Dual-agent review triggered for: ${fileName}`,
      JSON.stringify(reviewTask, null, 2)
    );

    return true;
  } catch (error) {
    console.error('Failed to trigger dual-agent review:', error);
    return false;
  }
}

/**
 * Write an implementation document to project-docs/implementations/
 * @param params Implementation parameters including topic, content, Jira issues, tags, and reviewers
 * @returns Result containing file path, git hash, linked issues, and review status
 * @throws Error if topic or content is empty, or if environment is misconfigured
 */
async function writeImplementation(
  params: WriteImplementationParams
): Promise<WriteImplementationResult> {
  if (!params.topic || params.topic.trim().length === 0) {
    throw new Error('topic parameter is required and must not be empty');
  }

  if (!params.content || params.content.trim().length === 0) {
    throw new Error('content parameter is required and must not be empty');
  }

  const { docsPath } = await validateEnvironment();

  const fileName = generateFileName(params.topic);

  const implDir = path.join(docsPath, 'implementations');
  if (!fs.existsSync(implDir)) {
    fs.mkdirSync(implDir, { recursive: true });
  }

  const documentContent = formatImplementationDocument(params, fileName);

  const filePath = path.join(implDir, fileName);

  try {
    fs.writeFileSync(filePath, documentContent, 'utf-8');
  } catch (error) {
    throw new Error(
      `Failed to write implementation file: ${filePath}\n${error}`
    );
  }

  let gitHash = 'staged';
  try {
    gitHash = await stageGitChanges(docsPath, fileName);
  } catch (error) {
    console.warn('Could not stage git changes:', error);
  }

  const linkedIssues = await linkJiraIssues(
    params.relatedIssues || [],
    fileName
  );

  const reviewTriggered = await triggerDualAgentReview(params, fileName);

  return {
    filePath,
    fileName,
    gitHash,
    dualReviewTriggered: reviewTriggered,
    linkedIssues,
    message: `Implementation document created: ${fileName}`,
    timestamp: new Date().toISOString(),
  };
}

// Main execution
const params: WriteImplementationParams = JSON.parse(process.argv[2] || '{}');

writeImplementation(params)
  .then((result) => {
    console.log(JSON.stringify(result, null, 2));
    process.exit(0);
  })
  .catch((error) => {
    console.error(JSON.stringify({ error: error.message }, null, 2));
    process.exit(1);
  });
