#!/usr/bin/env npx ts-node

/**
 * Write Design Skill
 * Captures brainstorming outputs and writes design documents to project-docs
 *
 * Usage:
 *   npx tsx .claude/skills/project-docs/write-design.ts '{
 *     "topic": "Authentication System Redesign",
 *     "content": "## Overview\n\nComplete redesign of the authentication...",
 *     "sections": ["OAuth2 Integration", "Token Management"],
 *     "tags": ["security", "authentication"],
 *     "reviewers": ["alice@platform.example.com"]
 *   }'
 */

import * as fs from 'fs';
import * as path from 'path';
import { exec } from 'child_process';
import { promisify } from 'util';

const execAsync = promisify(exec);

interface WriteDesignParams {
  topic: string;
  content: string;
  sections?: string[];
  tags?: string[];
  reviewers?: string[];
}

interface WriteDesignResult {
  filePath: string;
  fileName: string;
  gitHash?: string;
  dualReviewTriggered: boolean;
  message: string;
  timestamp: string;
}

async function validateEnvironment(): Promise<{
  docsPath: string;
  projectRoot: string;
}> {
  const docsPath = process.env.TENANT_DOCS_PATH;
  const projectRoot = process.env.PROJECT_ROOT;

  if (!docsPath) {
    throw new Error(
      'TENANT_DOCS_PATH environment variable not set. ' +
        'Set to absolute path of project-docs repository.'
    );
  }

  if (!projectRoot) {
    throw new Error(
      'PROJECT_ROOT environment variable not set. ' +
        'Set to absolute path of the platform project root.'
    );
  }

  if (!fs.existsSync(docsPath)) {
    throw new Error(
      `TENANT_DOCS_PATH does not exist: ${docsPath}\n` +
        'Verify the path is correct and accessible.'
    );
  }

  if (!fs.existsSync(projectRoot)) {
    throw new Error(
      `PROJECT_ROOT does not exist: ${projectRoot}\n` +
        'Verify the path is correct and accessible.'
    );
  }

  return { docsPath, projectRoot };
}

function generateFileName(topic: string): string {
  const date = new Date().toISOString().split('T')[0]; // YYYY-MM-DD
  const slug = topic
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-');

  return `${date}-${slug}.md`;
}

function formatDesignDocument(
  params: WriteDesignParams,
  fileName: string
): string {
  const timestamp = new Date().toISOString();
  const sections = params.sections || [];
  const tags = params.tags || [];

  let frontmatter = `---
title: "${params.topic}"
date: ${timestamp}
type: design
status: draft
tags: [${tags.map((t) => `"${t}"`).join(', ')}]
---

`;

  let body = `# ${params.topic}\n\n`;
  body += `**Date**: ${timestamp.split('T')[0]}\n`;
  body += `**Status**: Draft (awaiting dual-agent review)\n`;
  body += `**File**: \`designs/${fileName}\`\n\n`;

  if (params.reviewers && params.reviewers.length > 0) {
    body += `**Assigned Reviewers**: ${params.reviewers.join(', ')}\n\n`;
  }

  if (sections.length > 0) {
    body += `## Key Sections\n\n`;
    body += sections.map((s) => `- ${s}`).join('\n');
    body += '\n\n';
  }

  body += `## Content\n\n${params.content}\n\n`;
  body += `---\n\n`;
  body += `**Document generated by write-design.ts skill**\n`;

  return frontmatter + body;
}

async function stageGitChanges(
  docsPath: string,
  fileName: string
): Promise<string> {
  try {
    const designPath = path.join(docsPath, 'designs', fileName);

    await execAsync(`git add "${designPath}"`, { cwd: docsPath });

    const { stdout } = await execAsync(`git ls-files -s "${designPath}"`, {
      cwd: docsPath,
    });

    const hash = stdout.split(/\s+/)[1];

    return hash || 'staged';
  } catch (error) {
    console.warn('Could not retrieve git hash for staged file:', error);
    return 'staged';
  }
}

async function triggerDualAgentReview(
  params: WriteDesignParams,
  fileName: string
): Promise<boolean> {
  try {
    const reviewTask = {
      type: 'design_review',
      file: fileName,
      topic: params.topic,
      reviewers: params.reviewers || ['agent:researcher', 'agent:analyst'],
      timestamp: new Date().toISOString(),
      status: 'pending',
    };

    console.log(
      `[INFO] Dual-agent review triggered for: ${fileName}`,
      JSON.stringify(reviewTask, null, 2)
    );

    return true;
  } catch (error) {
    console.error('Failed to trigger dual-agent review:', error);
    return false;
  }
}

/**
 * Write a design document to project-docs/designs/
 * @param params Design document parameters including topic, content, tags, and reviewers
 * @returns Result containing file path, git hash, and review status
 * @throws Error if topic or content is empty, or if environment is misconfigured
 */
async function writeDesign(
  params: WriteDesignParams
): Promise<WriteDesignResult> {
  if (!params.topic || params.topic.trim().length === 0) {
    throw new Error('topic parameter is required and must not be empty');
  }

  if (!params.content || params.content.trim().length === 0) {
    throw new Error('content parameter is required and must not be empty');
  }

  const { docsPath } = await validateEnvironment();

  const fileName = generateFileName(params.topic);

  const designsDir = path.join(docsPath, 'designs');
  if (!fs.existsSync(designsDir)) {
    fs.mkdirSync(designsDir, { recursive: true });
  }

  const documentContent = formatDesignDocument(params, fileName);

  const filePath = path.join(designsDir, fileName);

  try {
    fs.writeFileSync(filePath, documentContent, 'utf-8');
  } catch (error) {
    throw new Error(`Failed to write design file: ${filePath}\n${error}`);
  }

  let gitHash = 'staged';
  try {
    gitHash = await stageGitChanges(docsPath, fileName);
  } catch (error) {
    console.warn('Could not stage git changes:', error);
  }

  const reviewTriggered = await triggerDualAgentReview(params, fileName);

  return {
    filePath,
    fileName,
    gitHash,
    dualReviewTriggered: reviewTriggered,
    message: `Design document created: ${fileName}`,
    timestamp: new Date().toISOString(),
  };
}

// Main execution
const params: WriteDesignParams = JSON.parse(process.argv[2] || '{}');

writeDesign(params)
  .then((result) => {
    console.log(JSON.stringify(result, null, 2));
    process.exit(0);
  })
  .catch((error) => {
    console.error(JSON.stringify({ error: error.message }, null, 2));
    process.exit(1);
  });
